security:
  oauth2:
    client:
      clientId: 633959467299-04qkj12cjhepppl1eoar54p5lq3iht5t.apps.googleusercontent.com
      clientSecret: kID9AY_GAeXG6Ycj51n6nuGs
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
